name: Self-Hosted-workflow Test1

on:
  workflow_dispatch:

jobs:
  testRunner:
    runs-on: [self-hosted]
    steps:

      - uses: actions/checkout@v3

      - name: Display Azure-CLI Version
        run: az --version

      - name: Show Public IP
        run: wget -q -O- http://ipecho.net/plain

      - name: Show Private IP
        run: hostname -I | awk '{print $1}'

      - name: Sleep
        run: sleep 2m
