name: Self-Hosted-workflow

on:
  workflow_dispatch:

jobs:
  testRunner:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Display Azure-CLI Version
        run: az --version

      - name: Show IP
        run: wget -q -O- http://ipecho.net/plain

      - name: Sleep
        run: sleep 2m
